"""empty message

Revision ID: 3077b0ae2e59
Revises: 5a5099579dbb
Create Date: 2023-10-13 15:15:37.120595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3077b0ae2e59'
down_revision = '5a5099579dbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_date', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_detail', schema=None) as batch_op:
        batch_op.drop_column('order_date')

    op.drop_table('contact_messages')
    # ### end Alembic commands ###
