"""empty message

Revision ID: 80036232136d
Revises: dee6c0ea0f5e
Create Date: 2023-10-27 10:06:04.367740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80036232136d'
down_revision = 'dee6c0ea0f5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('order_comments',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=2000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('order_comments',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
