"""empty message

Revision ID: cda7f7840c20
Revises: 082c3fd0525f
Create Date: 2023-10-12 11:25:05.619964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda7f7840c20'
down_revision = '082c3fd0525f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discount_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('used_discount_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('discount_code_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['discount_code_id'], ['discount_code.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('order_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('discount_code_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'discount_code', ['discount_code_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone_number')
        batch_op.drop_column('address')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('discount_code_id')
        batch_op.drop_column('order_date')
        batch_op.drop_column('payment_method')

    op.drop_table('used_discount_code')
    op.drop_table('discount_code')
    # ### end Alembic commands ###
