"""empty message

Revision ID: dee6c0ea0f5e
Revises: ffa6ddbc563a
Create Date: 2023-10-24 20:37:02.062059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dee6c0ea0f5e'
down_revision = 'ffa6ddbc563a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(length=100), nullable=True))
        batch_op.alter_column('menu_description',
               existing_type=sa.VARCHAR(length=9999),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_detail', schema=None) as batch_op:
        batch_op.alter_column('menu_description',
               existing_type=sa.VARCHAR(length=9999),
               nullable=True)
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###
