"""empty message

Revision ID: ffa6ddbc563a
Revises: e7bc381519f5
Create Date: 2023-10-24 20:07:45.774889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffa6ddbc563a'
down_revision = 'e7bc381519f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_description', sa.String(length=9999), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_detail', schema=None) as batch_op:
        batch_op.drop_column('menu_description')

    # ### end Alembic commands ###
